wandb_version: 1

batch_size:
  value: 32
cnn_kernel_regularizer:
  value: 0.04221722224424535
dense_kernel_regularizer:
  value: 0.08499539012065649
dropout_rate:
  value: 0.43946371350924573
image_size:
  value: 224
kernel_size:
  value: 5
learning_rate:
  value: 0.007300088880821333
num_filters:
  value: 16
pool_size:
  value: 3
unit_1:
  value: 64
unit_2:
  value: 128
